site:
  title: ownCloud User Interfaces
  url: https://doc.owncloud.com
  start_page: webui::index.adoc

content:
  sources:
  - url: .
    branches:
    - HEAD
  # the docs-server git is just present for the test build to satisfy used references
  # the real build is made in the docs repo using correct values
  - url: https://github.com/owncloud/docs-server.git
    branches:
    - master

ui:
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   global attributes loaded via antora extension
    latest-webui-version: 'next'    # do not change
    previous-webui-version: 'next'  # do not change
#   server
    latest-server-version: 'next'   # do not change
    previous-server-version: 'next' # do not change
    current-server-version: 'next'  # do not change
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki # integrated via npm

antora:
  extensions:
    - ./ext-antora/generate-index.js
    #- ./ext-antora/comp-version.js
    - require: ./ext-antora/load-global-site-attributes.js
      attributefile: https://raw.githubusercontent.com/owncloud/docs/refs/heads/master/global-attributes.yml
      #attributefile: ./global-attributes.yml
      enabled: true
    # for testing only, prints out attributes used
    # use only one or the other, output can be big
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js
